"<script setup lang="ts">
import { ref, computed } from 'vue'
import { jsPDF } from 'jspdf'
import type { Project, AuditJob } from '@/types'

const props = defineProps<{
  project: Project | null
  audit: AuditJob | null
}>()

const emit = defineEmits<{ close: [] }>()
const exporting = ref(false)

const fullReport = computed(() => {
  if (!props.audit || !props.project) return null
  return {
    project: props.project,
    audit: props.audit,
    generatedAt: new Date().toLocaleString(),
  }
})

async function exportPDF() {
  if (!fullReport.value) return
  exporting.value = true

  try {
    const doc = new jsPDF('p', 'mm', 'a4')
    const pageWidth = doc.internal.pageSize.getWidth()
    let y = 20

    // Title
    doc.setFontSize(24)
    doc.setTextColor(99, 102, 241)
    doc.text('QA-Suite Audit Report', pageWidth / 2, y, { align: 'center' })
    y += 10

    // Subtitle
    doc.setFontSize(12)
    doc.setTextColor(107, 114, 128)
    doc.text(`Generated: ${fullReport.value.generatedAt}`, pageWidth / 2, y, { align: 'center' })
    y += 15

    // Project Info
    doc.setFontSize(16)
    doc.setTextColor(31, 41, 55)
    doc.text('Project Information', 20, y)
    y += 8

    doc.setFontSize(11)
    doc.setTextColor(55, 65, 81)
    doc.text(`Name: ${fullReport.value.project.name}`, 25, y)
    y += 7
    doc.text(`Target URL: ${fullReport.value.project.targetUrl}`, 25, y)
    y += 7
    doc.text(`Auth Type: ${fullReport.value.project.authSettings.authType}`, 25, y)
    y += 7
    doc.text(`Status: ${fullReport.value.audit.status.toUpperCase()}`, 25, y)
    y += 15

    // Performance Scores
    doc.setFontSize(16)
    doc.setTextColor(31, 41, 55)
    doc.text('Performance Scores', 20, y)
    y += 8

    const scores = fullReport.value.audit.performanceSummary
    const scoreItems = [
      { label: 'Performance', value: scores.performance },
      { label: 'Accessibility', value: scores.accessibility },
      { label: 'SEO', value: scores.seo },
      { label: 'Best Practices', value: scores.bestPractices },
    ]

    doc.setFontSize(11)
    for (const item of scoreItems) {
      const color = item.value >= 90 ? [34, 197, 94] : item.value >= 50 ? [245, 158, 11] : [239, 68, 68]
      doc.setTextColor(color[0], color[1], color[2])
      doc.text(`${item.label}: ${item.value}/100`, 25, y)
      y += 7
    }
    y += 10

    // Security Summary
    doc.setFontSize(16)
    doc.setTextColor(31, 41, 55)
    doc.text('Security Scan Summary', 20, y)
    y += 8

    doc.setFontSize(11)
    const sec = fullReport.value.audit.securitySummary
    doc.setTextColor(239, 68, 68)
    doc.text(`High Risk Alerts: ${sec.highAlerts}`, 25, y); y += 7
    doc.setTextColor(245, 158, 11)
    doc.text(`Medium Risk Alerts: ${sec.mediumAlerts}`, 25, y); y += 7
    doc.setTextColor(59, 130, 246)
    doc.text(`Low Risk Alerts: ${sec.lowAlerts}`, 25, y); y += 7

    if (sec.missingHeaders.length > 0) {
      doc.setTextColor(239, 68, 68)
      doc.text(`Missing Headers: ${sec.missingHeaders.join(', ')}`, 25, y)
      y += 7
    }
    y += 10

    // SEO Summary
    doc.setFontSize(16)
    doc.setTextColor(31, 41, 55)
    doc.text('SEO Crawl Summary', 20, y)
    y += 8

    doc.setFontSize(11)
    doc.setTextColor(55, 65, 81)
    doc.text(`Pages Crawled: ${fullReport.value.audit.seoSummary.pageCount}`, 25, y)
    y += 7
    doc.setTextColor(239, 68, 68)
    doc.text(`SEO Issues Found: ${fullReport.value.audit.seoSummary.totalErrors}`, 25, y)
    y += 15

    // Footer
    doc.setFontSize(9)
    doc.setTextColor(156, 163, 175)
    doc.text('Generated by QA-Suite - Intelligent QA Platform', pageWidth / 2, 290, { align: 'center' })

    doc.save(`qa-audit-report-${fullReport.value.project.name.replace(/\s+/g, '-').toLowerCase()}.pdf`)
  } catch (err) {
    console.error('PDF export failed:', err)
  } finally {
    exporting.value = false
  }
}

function printReport() {
  window.print()
}
</script>

<template>
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
    <div class="card w-full max-w-2xl max-h-[80vh] overflow-y-auto">
      <div class="card-header flex items-center justify-between">
        <h2 class="text-lg font-semibold">📄 Export Report</h2>
        <button @click="emit('close')" class="text-gray-400 hover:text-gray-600">✕</button>
      </div>

      <div class="card-body space-y-6">
        <!-- Report Preview -->
        <div v-if="fullReport" class="space-y-4">
          <div class="rounded-lg bg-gray-50 p-4">
            <h3 class="font-semibold text-gray-900">{{ fullReport.project.name }}</h3>
            <p class="text-sm text-gray-500">{{ fullReport.project.targetUrl }}</p>
            <p class="text-xs text-gray-400 mt-1">Generated: {{ fullReport.generatedAt }}</p>
          </div>

          <div>
            <h4 class="text-sm font-medium text-gray-700 mb-2">Performance Scores</h4>
            <div class="grid grid-cols-2 gap-2">
              <div v-for="(score, key) in fullReport.audit.performanceSummary" :key="key" class="rounded bg-white border p-3 text-center">
                <p class="text-lg font-bold" :class="score >= 90 ? 'text-green-600' : score >= 50 ? 'text-yellow-600' : 'text-red-600'">
                  {{ score }}
                </p>
                <p class="text-xs text-gray-500 capitalize">{{ key }}</p>
              </div>
            </div>
          </div>

          <div>
            <h4 class="text-sm font-medium text-gray-700 mb-2">Security Alerts</h4>
            <div class="flex gap-2">
              <span class="badge-danger">{{ fullReport.audit.securitySummary.highAlerts }} High</span>
              <span class="badge-warning">{{ fullReport.audit.securitySummary.mediumAlerts }} Medium</span>
              <span class="badge-info">{{ fullReport.audit.securitySummary.lowAlerts }} Low</span>
            </div>
          </div>
        </div>

        <div v-else class="text-center py-8 text-gray-500">
          No audit data available. Run an audit first.
        </div>

        <!-- Actions -->
        <div class="flex justify-end gap-3">
          <button @click="emit('close')" class="btn-secondary">Cancel</button>
          <button @click="printReport" class="btn-secondary">🖨️ Print</button>
          <button @click="exportPDF" class="btn-primary" :disabled="exporting || !fullReport">
            <span v-if="exporting" class="animate-spin">⟳</span>
            {{ exporting ? 'Exporting...' : '📥 Download PDF' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style>
@media print {
  body * {
    visibility: hidden;
  }
  .card, .card * {
    visibility: visible;
  }
  .card {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
  }
}
</style>
"
